### ISSUE TITLE
Microscopic Polyangiitis

### ISSUE THREAD

**Issue by rh357** [Ossus/eponyms-touch#16]
It's similar to Werger's Granulomatosis, but is not the same disorder. Both are a form of ANCA vasculitis and the treatment regimen is the same, but Wergerner's is c-ANCA and MPA is p-ANCA. There's also the distinction between MPO and PR3 antibodies, but not sure if you need that much detail. I'm a nursing student with this condition so I was surprised that tou didn't have it already.

**Comment by andrewjyee** [comment]
In the next release, I clarify that Wegener's granulomatosis is also known as granulomatosis with polyangiitis.
