### ISSUE TITLE
Faget sign

### ISSUE THREAD

**Issue by DrPsychoWho** [Ossus/eponyms-touch#3]
Pulse-temperature dissociation. Normal HR accelerates 10bpm for each 1C ^ in temp. The exception of Liebermeister's rule. Seen commonly in yellow fever, dengue, tularemia, Q fever, salmonella typhi, lepto, brucellosis, viral myocarditis, bacterial endocarditis, diphtheria, legionnare's, mumps, influenza, malaria, fictitious fever, and chlamydia. 

Submitted by,
Glenn Todd Webb, MD

**Comment by andrewjyee** [comment]
This will be added to the next release.
